name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted


    steps:
        - name: Pull Docker Image
          env:
            DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          run: |
            COMMIT_SHA=$(git rev-parse --short=7 HEAD)
            sudo docker pull sumanthegdedocker/churn_model_api:$COMMIT_SHA
  
        - name: Delete Old Docker Container
          run: sudo docker rm -f churn_model_api-container || true
  
        - name: Run Docker Container
          env:
            DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          run: sudo docker run -it -d -p 8001:8001 --name churn_model_api-container sumanthegdedocker/churn_model_api:$COMMIT_SHA