name: Churn Prediction CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements/requirements.txt
          dagshub login --token c1f3b949a72ed6aeedcd73c6614bf1ff4a185aa5
          echo "Logged into dagshub"
          dvc pull


      - name: Model Training
        run: |
          python3 churn_model/train_pipeline.py

      - name: Model Prediction
        run: |
          python3 churn_model/predict.py

