name: Churn Prediction CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
          echo python3 --version
          python -m pip install --upgrade pip
          Python -m venv venv
          ./venv/Scripts/activate
          python -m pip install -r requirements/requirements.txt

      - name: Model Training
        run: |
          python bikeshare_model/train_pipeline.py

      - name: Model Prediction
        run: |
          python bikeshare_model/predict.py

